---
- name: Add ZooKeeper group
  group:
    name: zookeeper
    state: present

- name: Add ZooKeeper user
  user:
    name: zookeeper
    group: zookeeper

- name: Create ZooKeeper dir
  file:
    path: "{{ zookeeper_dir }}"
    state: directory
    mode: '0755'
    owner: zookeeper
    group: zookeeper

- name: Create ZooKeeper version dir
  file:
    path: "{{ zookeeper_dir }}/{{ zookeeper_version }}"
    state: directory
    mode: '0755'
    owner: zookeeper
    group: zookeeper
  register: zookeeper_version_dir

- name: Download and extract ZooKeeper
  unarchive:
    src: "https://archive.apache.org/dist/zookeeper/zookeeper-{{ zookeeper_version }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"
    dest: "{{ zookeeper_dir }}/{{ zookeeper_version }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
  when: zookeeper_version_dir.changed

- name: Create ZooKeeper data dir
  file:
    path: "{{ zookeeper_data_dir }}"
    state: directory
    owner: zookeeper
    group: zookeeper
    mode: '0755'

- name: Create ZooKeeper log dir
  file:
    path: "{{ zookeeper_log_dir }}"
    state: directory
    owner: zookeeper
    group: zookeeper
    mode: '0755'

- name: Create ZooKeeper service
  template:
    src: zookeeper.service.j2
    dest: "/etc/systemd/system/zookeeper.service"
    mode: '0644'
    owner: zookeeper
    group: zookeeper
  register: zookeeper_service
  notify: Update ZooKeeper
